import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FiSettings } from 'react-icons/fi';
import { ContextProvider, useContextState } from '@/contexts/ContextProvider'
import { ThemeSettings, Navbar } from '@/components';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { activeMenu, themeSettings, setThemeSettings, currentColor, currentMode } = useContextState();
  return (
    <>
      <Head>
        <title>KejaQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${currentMode === 'Dark' ? 'dark' : ''}`}>
        <div className='fixed md:static bg-main-bg dark:bg-main-dark-bg navbar w-full'>
          <Navbar />
        </div>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        {themeSettings && <ThemeSettings />}
      </main>
    </>
  )
}
